"use client"
import './globals.css'
import Navbar from "./components/Navbar";
import StarsCanvas from "./components/StarBackground";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({ children }){
  return (
    <html lang="en">

      <body className={`${inter.className} bg-[#030014] min-h-screen overflow-y-scroll overflow-x-hidden`}>
        <StarsCanvas />
        <div className="fixed top-0 w-full z-10 hidden " id="navbar"><Navbar /></div>
        {children}
        </body>
    </html>
  );
};
